name       : libcolord-gtk
version    : 0.3.0
release    : 7
source     :
    - https://www.freedesktop.org/software/colord/releases/colord-gtk-0.3.0.tar.xz : b9466656d66d9a6ffbc2dd04fa91c8f6af516bf9efaacb69744eec0f56f3c1d0
license    : GPL-2.0
component  : desktop.core
summary    : GTK+ convenience library for interacting with colord
description: |
    GTK+ convenience library for interacting with colord
replaces   :
    - devel : colord-gtk-devel
    - colord-gtk
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(lcms2)
    - vala
setup      : |
    %meson_configure -Ddocs=false -Dman=false
build      : |
    %ninja_build
install    : |
    %ninja_install
