name        : libcolord-gtk
version     : 0.1.26
release     : 4
source      :
    - https://www.freedesktop.org/software/colord/releases/colord-gtk-0.1.26.tar.xz : 28d00b7f157ea3e2ea5315387b2660fde82faba16674861c50465e55d61a3e45
license     : GPL-2.0
component   : desktop.core
summary     : GTK+ convenience library for interacting with colord
description : |
    GTK+ convenience library for interacting with colord
builddeps   :
    - pkgconfig(colord)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
